# Generated by Django 4.0.3 on 2022-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('EMPLOYEE', 'EMPLOYEE')], default='EMPLOYEE', max_length=60),
        ),
    ]
