# Generated by Django 4.0.3 on 2022-03-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
