# Generated by Django 4.0.3 on 2022-03-09 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 9, 22, 3, 14, 731686)),
        ),
    ]
