# Generated by Django 4.0.3 on 2022-03-10 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_employee_alter_task_date_of_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 10, 12, 9, 56, 907928)),
        ),
    ]
