# Generated by Django 4.0.3 on 2022-03-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_remove_task_user_task_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_of_submit',
        ),
    ]
