# Generated by Django 4.0.3 on 2022-03-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_rename_employee_task_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Employee',
            new_name='employee',
        ),
    ]
