# Generated by Django 4.0.3 on 2022-03-10 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_rename_employee_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 15, 17, 13, 94881)),
        ),
    ]
