# Generated by Django 4.0.3 on 2022-03-10 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_rename_employee_task_admin_alter_task_date_of_submit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 17, 14, 24, 174702)),
        ),
    ]
