# Generated by Django 4.0.3 on 2022-03-10 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_alter_task_date_of_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignTask',
        ),
        migrations.AddField(
            model_name='assigntask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 17, 31, 10, 372769)),
        ),
    ]
