# Generated by Django 4.0.3 on 2022-03-10 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0040_alter_task_date_of_submit_assigntask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntask',
            name='task_count',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 21, 9, 22, 652761)),
        ),
    ]
