# Generated by Django 4.0.3 on 2022-03-11 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0041_remove_assigntask_task_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 9, 12, 17, 239047)),
        ),
    ]
