# Generated by Django 4.0.3 on 2022-03-11 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0042_alter_task_date_of_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_submit',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 22, 18, 55, 660267)),
        ),
        migrations.DeleteModel(
            name='assignTask',
        ),
    ]
